sudo: false
dist: precise

language: c

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - intltool
      - libglib2.0-dev
      - libgtk-3-dev
      - libgtk2.0-dev
      - nettle-dev
      - libmbedtls-dev
      - linux-libc-dev
      - librsvg2-bin

env:
  - WITH_GTK=3.0
  - WITH_GTK=2.0

script:
  - ./autogen.sh
  - export DISTCHECK_CONFIGURE_FLAGS=$(echo --with-gtk=${WITH_GTK} --enable-{debug,mbedtls,nettle,linux-crypto} --disable-dependency-tracking)
  - ./configure ${DISTCHECK_CONFIGURE_FLAGS}
  - make distcheck VERBOSE=1
