dist: xenial

language: c

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - intltool
      - libglib2.0-dev
      - libgtk-3-dev
      - libgcrypt20-dev
      - nettle-dev
      - libb2-dev
      - libmbedtls-dev
      - libmhash-dev
      - linux-libc-dev
      - librsvg2-bin
      - at-spi2-core
      - libnautilus-extension-dev
      - libnemo-extension-dev

env:
  - WITH_GTK=3.0

script:
  - ./autogen.sh
  - export DISTCHECK_CONFIGURE_FLAGS=$(echo
      --with-gtk=${WITH_GTK}
      --enable-debug
      --enable-blake2
      --enable-gcrypt
      --enable-glib-checksums
      --enable-mbedtls
      --enable-mhash
      --enable-nettle
      --enable-linux-crypto
      --enable-nautilus
      --enable-nemo
      --disable-dependency-tracking
      )
  - ./configure ${DISTCHECK_CONFIGURE_FLAGS}
  - make -j$(nproc) VERBOSE=1 DESTDIR=$(mktemp -d) distcheck
