sudo: required
dist: trusty

language: c

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - intltool
      - libglib2.0-dev
      - libgtk-3-dev
      - libgtk2.0-dev
      - nettle-dev
      - libnss3-dev
      - libpolarssl-dev
      - linux-libc-dev

env:
  - WITH_GTK=3.0
  - WITH_GTK=2.0

script:
  - ./autogen.sh
  - ./configure --with-gtk=${WITH_GTK} --enable-{nettle,nss,polarssl,linux-crypto}
  - make
