dist: xenial

language: c

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - intltool
      - libglib2.0-dev
      - libgtk-3-dev
      - libgtk2.0-dev
      - libgcrypt20-dev
      - nettle-dev
      - linux-libc-dev
      - librsvg2-bin
      - at-spi2-core

env:
  - WITH_GTK=3.0
  - WITH_GTK=2.0

script:
  - ./autogen.sh
  - export DISTCHECK_CONFIGURE_FLAGS=$(echo --with-gtk=${WITH_GTK} --enable-{debug,glib-checksums,nettle,linux-crypto} --disable-blake2 --disable-dependency-tracking)
  - ./configure ${DISTCHECK_CONFIGURE_FLAGS}
  - make -j$(nproc) distcheck VERBOSE=1
