name: gtkhash
adopt-info: gtkhash
version: git
grade: devel
base: core18
confinement: strict

apps:
  gtkhash:
    command: bin/gtkhash
    desktop: share/applications/gtkhash.desktop
    common-id: org.gtkhash.gtkhash
    extensions: [ gnome-3-28 ]
    plugs:
      - gsettings
      - home

parts:
  gtkhash:
    source: https://github.com/tristanheaven/gtkhash.git
    plugin: autotools
    build-packages:
      - pkg-config
      - libtool
      - gettext
      - intltool
      - libglib2.0-dev
      - libgtk-3-dev
      - libgcrypt20-dev
      - libb2-dev
      - librsvg2-bin
      - libxml2-utils
    stage-packages:
      - libgtk-3-0
      - libgcrypt20
      - libb2-1
    parse-info: [ share/metainfo/gtkhash.appdata.xml ]
